import React from 'react';
import { Outlet } from 'react-router-dom';
import Navbar from './Navbar.jsx';
import Sidebar from './Sidebar.jsx';

export const Layout = () => {

  return (
    <div className=' min-h-screen grid grid-rows-[50px_auto] antialised' style={{fontFamily:"Roboto"}}>
      
      <header>
        <Navbar/>
      </header>

      {/* <div className=' grid lg:grid-cols-[13rem_auto] sm:grid-cols-[60px_auto]'> */}
      <div className=' flex '>
        <Sidebar/>

        <div className=' overflow-y-scroll h-[calc(100vh-50px)]'>   
          <Outlet/>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio vitae pariatur tempora dicta quidem atque vel eius corporis. Reprehenderit magnam est facilis impedit fuga ex voluptatibus debitis commodi molestias, dicta non, explicabo facere dolorum incidunt quasi cum qui, officia minus doloribus maxime. Necessitatibus, dolore fuga sint nulla eius error nostrum aut nemo sit quibusdam quidem, incidunt eligendi aperiam perspiciatis qui? Laboriosam illo commodi nemo voluptate iure exercitationem quia at fugit ea porro ipsum accusamus dolorem possimus ipsa, deleniti quasi vero reiciendis natus alias earum ducimus non? Esse soluta distinctio eligendi ipsam, at quidem quia, doloribus architecto, ducimus sint sit illum.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio vitae pariatur tempora dicta quidem atque vel eius corporis. Reprehenderit magnam est facilis impedit fuga ex voluptatibus debitis commodi molestias, dicta non, explicabo facere dolorum incidunt quasi cum qui, officia minus doloribus maxime. Necessitatibus, dolore fuga sint nulla eius error nostrum aut nemo sit quibusdam quidem, incidunt eligendi aperiam perspiciatis qui? Laboriosam illo commodi nemo voluptate iure exercitationem quia at fugit ea porro ipsum accusamus dolorem possimus ipsa, deleniti quasi vero reiciendis natus alias earum ducimus non? Esse soluta distinctio eligendi ipsam, at quidem quia, doloribus architecto, ducimus sint sit illum.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio vitae pariatur tempora dicta quidem atque vel eius corporis. Reprehenderit magnam est facilis impedit fuga ex voluptatibus debitis commodi molestias, dicta non, explicabo facere dolorum incidunt quasi cum qui, officia minus doloribus maxime. Necessitatibus, dolore fuga sint nulla eius error nostrum aut nemo sit quibusdam quidem, incidunt eligendi aperiam perspiciatis qui? Laboriosam illo commodi nemo voluptate iure exercitationem quia at fugit ea porro ipsum accusamus dolorem possimus ipsa, deleniti quasi vero reiciendis natus alias earum ducimus non? Esse soluta distinctio eligendi ipsam, at quidem quia, doloribus architecto, ducimus sint sit illum.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio vitae pariatur tempora dicta quidem atque vel eius corporis. Reprehenderit magnam est facilis impedit fuga ex voluptatibus debitis commodi molestias, dicta non, explicabo facere dolorum incidunt quasi cum qui, officia minus doloribus maxime. Necessitatibus, dolore fuga sint nulla eius error nostrum aut nemo sit quibusdam quidem, incidunt eligendi aperiam perspiciatis qui? Laboriosam illo commodi nemo voluptate iure exercitationem quia at fugit ea porro ipsum accusamus dolorem possimus ipsa, deleniti quasi vero reiciendis natus alias earum ducimus non? Esse soluta distinctio eligendi ipsam, at quidem quia, doloribus architecto, ducimus sint sit illum.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio vitae pariatur tempora dicta quidem atque vel eius corporis. Reprehenderit magnam est facilis impedit fuga ex voluptatibus debitis commodi molestias, dicta non, explicabo facere dolorum incidunt quasi cum qui, officia minus doloribus maxime. Necessitatibus, dolore fuga sint nulla eius error nostrum aut nemo sit quibusdam quidem, incidunt eligendi aperiam perspiciatis qui? Laboriosam illo commodi nemo voluptate iure exercitationem quia at fugit ea porro ipsum accusamus dolorem possimus ipsa, deleniti quasi vero reiciendis natus alias earum ducimus non? Esse soluta distinctio eligendi ipsam, at quidem quia, doloribus architecto, ducimus sint sit illum.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio vitae pariatur tempora dicta quidem atque vel eius corporis. Reprehenderit magnam est facilis impedit fuga ex voluptatibus debitis commodi molestias, dicta non, explicabo facere dolorum incidunt quasi cum qui, officia minus doloribus maxime. Necessitatibus, dolore fuga sint nulla eius error nostrum aut nemo sit quibusdam quidem, incidunt eligendi aperiam perspiciatis qui? Laboriosam illo commodi nemo voluptate iure exercitationem quia at fugit ea porro ipsum accusamus dolorem possimus ipsa, deleniti quasi vero reiciendis natus alias earum ducimus non? Esse soluta distinctio eligendi ipsam, at quidem quia, doloribus architecto, ducimus sint sit illum.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio vitae pariatur tempora dicta quidem atque vel eius corporis. Reprehenderit magnam est facilis impedit fuga ex voluptatibus debitis commodi molestias, dicta non, explicabo facere dolorum incidunt quasi cum qui, officia minus doloribus maxime. Necessitatibus, dolore fuga sint nulla eius error nostrum aut nemo sit quibusdam quidem, incidunt eligendi aperiam perspiciatis qui? Laboriosam illo commodi nemo voluptate iure exercitationem quia at fugit ea porro ipsum accusamus dolorem possimus ipsa, deleniti quasi vero reiciendis natus alias earum ducimus non? Esse soluta distinctio eligendi ipsam, at quidem quia, doloribus architecto, ducimus sint sit illum.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio vitae pariatur tempora dicta quidem atque vel eius corporis. Reprehenderit magnam est facilis impedit fuga ex voluptatibus debitis commodi molestias, dicta non, explicabo facere dolorum incidunt quasi cum qui, officia minus doloribus maxime. Necessitatibus, dolore fuga sint nulla eius error nostrum aut nemo sit quibusdam quidem, incidunt eligendi aperiam perspiciatis qui? Laboriosam illo commodi nemo voluptate iure exercitationem quia at fugit ea porro ipsum accusamus dolorem possimus ipsa, deleniti quasi vero reiciendis natus alias earum ducimus non? Esse soluta distinctio eligendi ipsam, at quidem quia, doloribus architecto, ducimus sint sit illum.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio vitae pariatur tempora dicta quidem atque vel eius corporis. Reprehenderit magnam est facilis impedit fuga ex voluptatibus debitis commodi molestias, dicta non, explicabo facere dolorum incidunt quasi cum qui, officia minus doloribus maxime. Necessitatibus, dolore fuga sint nulla eius error nostrum aut nemo sit quibusdam quidem, incidunt eligendi aperiam perspiciatis qui? Laboriosam illo commodi nemo voluptate iure exercitationem quia at fugit ea porro ipsum accusamus dolorem possimus ipsa, deleniti quasi vero reiciendis natus alias earum ducimus non? Esse soluta distinctio eligendi ipsam, at quidem quia, doloribus architecto, ducimus sint sit illum.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio vitae pariatur tempora dicta quidem atque vel eius corporis. Reprehenderit magnam est facilis impedit fuga ex voluptatibus debitis commodi molestias, dicta non, explicabo facere dolorum incidunt quasi cum qui, officia minus doloribus maxime. Necessitatibus, dolore fuga sint nulla eius error nostrum aut nemo sit quibusdam quidem, incidunt eligendi aperiam perspiciatis qui? Laboriosam illo commodi nemo voluptate iure exercitationem quia at fugit ea porro ipsum accusamus dolorem possimus ipsa, deleniti quasi vero reiciendis natus alias earum ducimus non? Esse soluta distinctio eligendi ipsam, at quidem quia, doloribus architecto, ducimus sint sit illum.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio vitae pariatur tempora dicta quidem atque vel eius corporis. Reprehenderit magnam est facilis impedit fuga ex voluptatibus debitis commodi molestias, dicta non, explicabo facere dolorum incidunt quasi cum qui, officia minus doloribus maxime. Necessitatibus, dolore fuga sint nulla eius error nostrum aut nemo sit quibusdam quidem, incidunt eligendi aperiam perspiciatis qui? Laboriosam illo commodi nemo voluptate iure exercitationem quia at fugit ea porro ipsum accusamus dolorem possimus ipsa, deleniti quasi vero reiciendis natus alias earum ducimus non? Esse soluta distinctio eligendi ipsam, at quidem quia, doloribus architecto, ducimus sint sit illum.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio vitae pariatur tempora dicta quidem atque vel eius corporis. Reprehenderit magnam est facilis impedit fuga ex voluptatibus debitis commodi molestias, dicta non, explicabo facere dolorum incidunt quasi cum qui, officia minus doloribus maxime. Necessitatibus, dolore fuga sint nulla eius error nostrum aut nemo sit quibusdam quidem, incidunt eligendi aperiam perspiciatis qui? Laboriosam illo commodi nemo voluptate iure exercitationem quia at fugit ea porro ipsum accusamus dolorem possimus ipsa, deleniti quasi vero reiciendis natus alias earum ducimus non? Esse soluta distinctio eligendi ipsam, at quidem quia, doloribus architecto, ducimus sint sit illum.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio vitae pariatur tempora dicta quidem atque vel eius corporis. Reprehenderit magnam est facilis impedit fuga ex voluptatibus debitis commodi molestias, dicta non, explicabo facere dolorum incidunt quasi cum qui, officia minus doloribus maxime. Necessitatibus, dolore fuga sint nulla eius error nostrum aut nemo sit quibusdam quidem, incidunt eligendi aperiam perspiciatis qui? Laboriosam illo commodi nemo voluptate iure exercitationem quia at fugit ea porro ipsum accusamus dolorem possimus ipsa, deleniti quasi vero reiciendis natus alias earum ducimus non? Esse soluta distinctio eligendi ipsam, at quidem quia, doloribus architecto, ducimus sint sit illum.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio vitae pariatur tempora dicta quidem atque vel eius corporis. Reprehenderit magnam est facilis impedit fuga ex voluptatibus debitis commodi molestias, dicta non, explicabo facere dolorum incidunt quasi cum qui, officia minus doloribus maxime. Necessitatibus, dolore fuga sint nulla eius error nostrum aut nemo sit quibusdam quidem, incidunt eligendi aperiam perspiciatis qui? Laboriosam illo commodi nemo voluptate iure exercitationem quia at fugit ea porro ipsum accusamus dolorem possimus ipsa, deleniti quasi vero reiciendis natus alias earum ducimus non? Esse soluta distinctio eligendi ipsam, at quidem quia, doloribus architecto, ducimus sint sit illum.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio vitae pariatur tempora dicta quidem atque vel eius corporis. Reprehenderit magnam est facilis impedit fuga ex voluptatibus debitis commodi molestias, dicta non, explicabo facere dolorum incidunt quasi cum qui, officia minus doloribus maxime. Necessitatibus, dolore fuga sint nulla eius error nostrum aut nemo sit quibusdam quidem, incidunt eligendi aperiam perspiciatis qui? Laboriosam illo commodi nemo voluptate iure exercitationem quia at fugit ea porro ipsum accusamus dolorem possimus ipsa, deleniti quasi vero reiciendis natus alias earum ducimus non? Esse soluta distinctio eligendi ipsam, at quidem quia, doloribus architecto, ducimus sint sit illum.
        </div>
      </div>

    </div>
  )
}
